package net.without_brains.echo_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2011-10-30T20:47:54.275+01:00
 * Generated source version: 2.4.3
 * 
 */
@WebServiceClient(name = "EchoService", 
                  wsdlLocation = "http://localhost:9292/echo_service.wsdl",
                  targetNamespace = "http://www.without-brains.net/echo_service") 
public class EchoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.without-brains.net/echo_service", "EchoService");
    public final static QName EchoPort = new QName("http://www.without-brains.net/echo_service", "EchoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9292/echo_service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EchoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9292/echo_service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EchoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EchoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EchoPortType
     */
    @WebEndpoint(name = "EchoPort")
    public EchoPortType getEchoPort() {
        return super.getPort(EchoPort, EchoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoPortType
     */
    @WebEndpoint(name = "EchoPort")
    public EchoPortType getEchoPort(WebServiceFeature... features) {
        return super.getPort(EchoPort, EchoPortType.class, features);
    }

}
