package net.without_brains.echo_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2011-10-30T20:47:54.263+01:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://www.without-brains.net/echo_service", name = "EchoPortType")
@XmlSeeAlso({net.without_brains.echo.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EchoPortType {

    @WebResult(name = "ReverseEchoResponse", targetNamespace = "http://www.without-brains.net/echo", partName = "parameter")
    @WebMethod(operationName = "ReverseEcho", action = "http://www.without-brains.net/echo_service#ReverseEcho")
    public net.without_brains.echo.EchoMessageType reverseEcho(
        @WebParam(partName = "parameter", name = "ReverseEchoRequest", targetNamespace = "http://www.without-brains.net/echo")
        net.without_brains.echo.EchoMessageType parameter
    );

    @WebResult(name = "EchoResponse", targetNamespace = "http://www.without-brains.net/echo", partName = "parameter")
    @WebMethod(operationName = "Echo", action = "http://www.without-brains.net/echo_service#Echo")
    public net.without_brains.echo.EchoMessageType echo(
        @WebParam(partName = "parameter", name = "EchoRequest", targetNamespace = "http://www.without-brains.net/echo")
        net.without_brains.echo.EchoMessageType parameter
    );
}
